# Generated by Django 3.2.4 on 2021-06-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
